services:
  - type: web
    name: zentra-api
    env: docker
    plan: free
    dockerfilePath: ./api/Dockerfile
    autoDeploy: true
    envVars:
      - key: KEEPA_KEY
        sync: false
      - key: KEEPA_DOMAIN
        value: "1"
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
  - type: web
    name: zentra-web
    env: docker
    plan: free
    dockerfilePath: ./web/Dockerfile
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: ""
